import * as fs from 'node:fs';
import * as path from 'node:path';
import { ensureDir, writeMarkdown } from '../utils/fs.js';
import type { FormatAdapter, FormatContext } from './types.js';

/**
 * Maps skill names to the analyzed files that provide their content.
 * Paths are relative to analyzedDir.
 */
const SKILL_SOURCES: Array<{
  name: string;
  description: string;
  analyzedFiles: string[];
}> = [
  {
    name: 'domain-model',
    description: 'Use when working with core domain entities, aggregates, and value objects',
    analyzedFiles: ['domain/bounded-contexts.md', 'domain/entities.md', 'domain/glossary.md'],
  },
  {
    name: 'business-rules',
    description: 'Use when implementing or validating business logic and constraints',
    analyzedFiles: ['rules/business-rules.md', 'rules/validation-rules.md'],
  },
  {
    name: 'api-contracts',
    description: 'Use when building or consuming API endpoints and their contracts',
    analyzedFiles: ['api/contracts.md', 'api/external-deps.md'],
  },
  {
    name: 'user-flows',
    description: 'Use when implementing user-facing features and interactions',
    analyzedFiles: ['flows/user-flows.md', 'flows/data-flows.md'],
  },
  {
    name: 'data-model',
    description: 'Use when working with database schemas, migrations, and data access',
    analyzedFiles: ['infra/data-storage.md', 'domain/entities.md'],
  },
  {
    name: 'security-auth',
    description: 'Use when implementing authentication, authorization, and security controls',
    analyzedFiles: ['rules/permissions.md'],
  },
  {
    name: 'infrastructure',
    description: 'Use when configuring infrastructure, deployments, and environment setup',
    analyzedFiles: ['infra/architecture.md'],
  },
  {
    name: 'migration-guide',
    description: 'Use when planning or executing migration from the legacy system',
    analyzedFiles: ['infra/architecture.md', 'domain/bounded-contexts.md'],
  },
];

function buildToolkitSection(recs: FormatContext['toolkitRecommendations']): string {
  if (!recs || recs.recommendations.length === 0) return '';

  const mcps = recs.recommendations.filter((r) => r.type === 'mcp');
  const skills = recs.recommendations.filter((r) => r.type === 'skill');
  const other = recs.recommendations.filter((r) => r.type !== 'mcp' && r.type !== 'skill');

  let section = '\n\n## Recommended MCPs\n\n';
  if (mcps.length > 0) {
    section += mcps.map((r) => `- **${r.package}** — ${r.description}`).join('\n');
  }
  if (skills.length > 0) {
    section += '\n\n## Recommended Skills\n\n';
    section += skills.map((r) => `- **${r.package || r.name}** — ${r.description}`).join('\n');
  }
  if (other.length > 0) {
    section += '\n\n## Other Recommended Tools\n\n';
    section += other.map((r) => `- **${r.name}** — ${r.description}`).join('\n');
  }

  return section;
}

function readFileOrEmpty(filePath: string): string {
  if (!fs.existsSync(filePath)) return '';
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch {
    return '';
  }
}

export class SuperpowersFormat implements FormatAdapter {
  name = 'superpowers';

  async package(specsDir: string, outputDir: string, context: FormatContext): Promise<void> {
    const { projectName, projectDescription, sddContent, analyzedDir } = context;

    // Create skill folders with SKILL.md populated from analyzed data
    for (const skill of SKILL_SOURCES) {
      const sections: string[] = [];

      for (const relPath of skill.analyzedFiles) {
        const content = readFileOrEmpty(path.join(analyzedDir, relPath));
        if (content) {
          const label = path.basename(relPath, '.md').replace(/-/g, ' ');
          sections.push(`## ${label}\n\n${content}`);
        }
      }

      const body = sections.length > 0
        ? sections.join('\n\n---\n\n')
        : `No analyzed data available for this skill. Run \`respec analyze\` first.`;

      writeMarkdown(
        path.join(outputDir, 'skills', skill.name, 'SKILL.md'),
        `---\nname: ${skill.name}\nuser-invocable: true\ndescription: ${skill.description}\n---\n\n# ${skill.name}\n\n${skill.description}.\n\n${body}\n`
      );
    }

    // CLAUDE.md
    const toolkitSection = buildToolkitSection(context.toolkitRecommendations);
    writeMarkdown(
      path.join(outputDir, 'CLAUDE.md'),
      `# ${projectName}\n\n${projectDescription}\n\n## Skills\n\nThis project uses Superpowers skills for structured AI assistance.\nAvailable skills are in the \`skills/\` directory.\n\n## Guidelines\n\n- Reference \`sdd.md\` for system design decisions\n- Use skills to get context-specific guidance\n- Follow the domain model and business rules strictly\n${toolkitSection}`
    );

    // sdd.md (already generated by sdd-gen, just ensure it exists)
    if (sddContent) {
      writeMarkdown(path.join(outputDir, 'sdd.md'), sddContent);
    }
  }
}
